In [2]:
#Importing Library

import pandas as pd

In [5]:
#Load Datasets

df = pd.read_csv("customer_demographics_contaminated.csv")

In [6]:
df

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24
...,...,...,...,...,...,...
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17
3196,0ef84cc6-0b4c-4c56-bdaa-d6b725ccc08e,40.0,Male,Lisaside,Medium,2022-07-23
3197,0ede97d1-bb46-452d-893e-b63f37da4fa8,NaN,Female,North Christinaport,High,2021-10-16
3198,43ec68f5-4305-4b40-8ced-a187d00bb3f5,26.0,Female,Carrilloport,Low,2022-09-26
3199,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09

In [10]:
#Dropping duplicate rows

df = df.drop_duplicates()
df

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24
...,...,...,...,...,...,...
3165,48313b18-ccdb-4946-b958-1ebfc92dcc2a,59.0,Male,South Andrea,High,2020-02-26
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,Unknown,Male,Gregoryfurt,High,2020-06-23
3183,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,55.0,Male,New Anthonyland,High,2022-07-23
3186,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,41.0,Female,Adrianhaven,Low,2024-01-10
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17

In [19]:
df.describe()

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
count,3023,2747,3023,3023,2738,3023
unique,3000,58,2,2696,3,1544
top,bbf7c36f-3745-4d3a-9e33-f927c2755f65,62.0,Female,Port Michael,High,2024-06-08
freq,2,70,1528,5,946,9

In [20]:
# checking for null 

df.isnull().sum()

CustomerID       0
Age            276
Gender           0
Location         0
IncomeLevel    285
SignupDate       0
dtype: int64

In [22]:
#Dropping rows with null values in Income Level column

df_clean = df.dropna(subset=["IncomeLevel"])
df_clean

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24
5,2de49c7c-32ae-4ba8-b058-622a090d7094,53.0,Female,Emilyville,Low,2022-02-13
...,...,...,...,...,...,...
3165,48313b18-ccdb-4946-b958-1ebfc92dcc2a,59.0,Male,South Andrea,High,2020-02-26
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,Unknown,Male,Gregoryfurt,High,2020-06-23
3183,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,55.0,Male,New Anthonyland,High,2022-07-23
3186,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,41.0,Female,Adrianhaven,Low,2024-01-10
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17

In [23]:
df_clean.isnull().sum()

CustomerID       0
Age            245
Gender           0
Location         0
IncomeLevel      0
SignupDate       0
dtype: int64

In [25]:
df_clean['Age'].value_counts()

Age
62.0       64
34.0       60
26.0       59
57.0       57
68.0       56
55.0       56
70.0       52
61.0       51
23.0       51
53.0       50
59.0       50
43.0       50
64.0       49
52.0       49
18.0       49
46.0       49
58.0       49
37.0       49
36.0       49
56.0       49
49.0       48
25.0       48
66.0       47
19.0       46
63.0       46
40.0       45
67.0       45
27.0       45
65.0       44
45.0       44
28.0       44
42.0       44
31.0       43
48.0       43
60.0       43
38.0       43
20.0       42
69.0       42
51.0       41
39.0       41
32.0       40
54.0       40
21.0       40
30.0       40
50.0       39
35.0       39
47.0       38
41.0       37
44.0       36
29.0       33
24.0       33
22.0       33
33.0       31
Unknown    29
150        26
-1         24
150.0       2
-1.0        1
Name: count, dtype: int64

In [60]:
# Convert the Age column to numeric
df_clean['Age'] = pd.to_numeric(df_clean['Age'], errors='coerce')

# Calculate the iqr
q1 = df_clean['Age'].quantile(0.25)
q3 = df_clean['Age'].quantile(0.75)
iqr = q3 - q1
iqr

np.float64(28.0)

In [61]:
# Calculating the lower limit and the Upper limit

lower_limit = q1 - iqr
upper_limit = q3 + iqr
lower_limit, upper_limit

(np.float64(3.0), np.float64(87.0))

In [62]:
# Calculate the mean age
mean_age = df_clean['Age'].mean()

# Replaces NaN with mean age
df_clean['Age'] = df_clean['Age'].fillna(mean_age)

mean_age

np.float64(45.497564935064936)

In [63]:
df_clean['Age'].value_counts()

Age
 45.497565     274
 62.000000      64
 34.000000      60
 26.000000      59
 57.000000      57
 68.000000      56
 55.000000      56
 70.000000      52
 61.000000      51
 23.000000      51
 53.000000      50
 59.000000      50
 43.000000      50
 64.000000      49
 52.000000      49
 18.000000      49
 46.000000      49
 58.000000      49
 37.000000      49
 36.000000      49
 56.000000      49
 49.000000      48
 25.000000      48
 66.000000      47
 19.000000      46
 63.000000      46
 40.000000      45
 67.000000      45
 27.000000      45
 65.000000      44
 45.000000      44
 28.000000      44
 42.000000      44
 31.000000      43
 48.000000      43
 60.000000      43
 38.000000      43
 20.000000      42
 69.000000      42
 51.000000      41
 39.000000      41
 32.000000      40
 54.000000      40
 21.000000      40
 30.000000      40
 50.000000      39
 35.000000      39
 47.000000      38
 41.000000      37
 44.000000      36
 29.000000      33
 24.000000      33
 22.000000      33
 33.000000      31
 150.000000     28
-1.000000       25
Name: count, dtype: int64

In [64]:
df_clean.isnull().sum()

CustomerID     0
Age            0
Gender         0
Location       0
IncomeLevel    0
SignupDate     0
dtype: int64

In [65]:
#Removes outliers in age that are below lower limit and above upper limit

df_clean = df_clean[(df_clean['Age'] >= lower_limit) & (df_clean['Age'] <= upper_limit)]
df_clean['Age'].value_counts()

Age
45.497565    274
62.000000     64
34.000000     60
26.000000     59
57.000000     57
68.000000     56
55.000000     56
70.000000     52
61.000000     51
23.000000     51
53.000000     50
59.000000     50
43.000000     50
64.000000     49
52.000000     49
18.000000     49
46.000000     49
58.000000     49
37.000000     49
36.000000     49
56.000000     49
49.000000     48
25.000000     48
66.000000     47
19.000000     46
63.000000     46
40.000000     45
67.000000     45
27.000000     45
65.000000     44
45.000000     44
28.000000     44
42.000000     44
31.000000     43
48.000000     43
60.000000     43
38.000000     43
20.000000     42
69.000000     42
51.000000     41
39.000000     41
32.000000     40
54.000000     40
21.000000     40
30.000000     40
50.000000     39
35.000000     39
47.000000     38
41.000000     37
44.000000     36
29.000000     33
24.000000     33
22.000000     33
33.000000     31
Name: count, dtype: int64

In [66]:
df_clean

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.000000,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,45.497565,Female,Castilloport,High,2020-07-21
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.000000,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.000000,Female,Jessebury,High,2023-08-24
5,2de49c7c-32ae-4ba8-b058-622a090d7094,53.000000,Female,Emilyville,Low,2022-02-13
...,...,...,...,...,...,...
3165,48313b18-ccdb-4946-b958-1ebfc92dcc2a,59.000000,Male,South Andrea,High,2020-02-26
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,45.497565,Male,Gregoryfurt,High,2020-06-23
3183,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,55.000000,Male,New Anthonyland,High,2022-07-23
3186,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,41.000000,Female,Adrianhaven,Low,2024-01-10
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.000000,Female,Roberttown,Medium,2023-02-17

In [78]:
df_clean['Age'] = df_clean['Age'].round()
df_clean

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,45.0,Female,Castilloport,High,2020-07-21
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24
5,2de49c7c-32ae-4ba8-b058-622a090d7094,53.0,Female,Emilyville,Low,2022-02-13
...,...,...,...,...,...,...
3165,48313b18-ccdb-4946-b958-1ebfc92dcc2a,59.0,Male,South Andrea,High,2020-02-26
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,45.0,Male,Gregoryfurt,High,2020-06-23
3183,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,55.0,Male,New Anthonyland,High,2022-07-23
3186,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,41.0,Female,Adrianhaven,Low,2024-01-10
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17

In [79]:
# Export the DataFrame to a CSV file
df_clean.to_csv('customer_demographics_cleaned.csv', index=False)