In [3]:
#Import Libraries

import pandas as pd

In [4]:
#Load Datasets

df = pd.read_csv("customer_transactions_contaminated.csv")

In [3]:
df

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer
...,...,...,...,...,...,...
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3197,34e3f558-622e-4d6b-8d5d-07ab632e1b95,db0a4640-ea96-4fcd-989b-b71ba767529c,2022-12-26,NaN,Home & Garden,PayPal
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card
3199,d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9,6c47f481-3a5c-49bc-ab1d-2b198394b2e8,2023-06-20,NaN,Electronics,Debit Card

In [4]:
#Dropping duplicate rows

df = df.drop_duplicates()
df

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer
...,...,...,...,...,...,...
3153,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,974.25,Electronics,Debit Card
3157,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,10/08/2022,50.07,Automotive,Bank Transfer
3164,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,20/07/2022,272.68,Clothing,Debit Card
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [5]:
# checking for null 

df.isnull().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             283
ProductCategory    282
PaymentMethod        0
dtype: int64

In [5]:
#Dropping rows with null values in Product Category column

df_clean = df.dropna(subset=["ProductCategory"])
df_clean

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer
...,...,...,...,...,...,...
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3197,34e3f558-622e-4d6b-8d5d-07ab632e1b95,db0a4640-ea96-4fcd-989b-b71ba767529c,2022-12-26,NaN,Home & Garden,PayPal
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card
3199,d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9,6c47f481-3a5c-49bc-ab1d-2b198394b2e8,2023-06-20,NaN,Electronics,Debit Card

In [6]:
df_clean.isnull().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             277
ProductCategory      0
PaymentMethod        0
dtype: int64

In [11]:
df_clean = df_clean[df_clean['Amount'] > 0]
df_clean

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer
...,...,...,...,...,...,...
3189,79a5eedf-99cd-4151-9007-8d0904daf592,ed9e281d-c0df-44a3-b18f-6aa4f2e2063d,2023-03-07,482.63,Health & Beauty,Credit Card
3191,b69f9ff9-837b-4582-8187-1f2f28c6e2d2,5df1d055-556f-4ffd-b50a-c1465fb4a0c1,2022-11-02,324.11,Electronics,PayPal
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card

In [12]:
df_clean.isnull().sum()

CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

In [13]:
df['TransactionDate'] = pd.to_datetime(df['TransactionDate'], format='mixed', errors='coerce')

df['TransactionDate'] = df['TransactionDate'].dt.strftime('%Y/%m/%d')

In [16]:
df_clean.dtypes

CustomerID             str
TransactionID          str
TransactionDate        str
Amount             float64
ProductCategory        str
PaymentMethod          str
dtype: object

In [22]:
# Standardize separators to slashes
s = df['TransactionDate'].astype(str).str.replace('-', '/')

# Create an empty series for the results
parsed_dates = pd.Series(pd.NaT, index=df.index)

# Group 1: Rows where the year is first (starts with 4 digits, e.g., 2026/...)
is_year_first = s.str.match(r'^\d{4}')
parsed_dates[is_year_first] = pd.to_datetime(s[is_year_first], errors='coerce')

# Group 2: Rows where the day is first (e.g., 31/12/2026)
is_day_first = ~is_year_first & s.notna()
parsed_dates[is_day_first] = pd.to_datetime(s[is_day_first], dayfirst=True, errors='coerce')

# Convert back to standard YYYY/MM/DD format string
df_clean['TransactionDate'] = parsed_dates.dt.strftime('%Y/%m/%d')

In [23]:
df_clean

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024/05/15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023/04/26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022/09/23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024/04/15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024/06/03,590.52,Home & Garden,Bank Transfer
...,...,...,...,...,...,...
3189,79a5eedf-99cd-4151-9007-8d0904daf592,ed9e281d-c0df-44a3-b18f-6aa4f2e2063d,2023/03/07,482.63,Health & Beauty,Credit Card
3191,b69f9ff9-837b-4582-8187-1f2f28c6e2d2,5df1d055-556f-4ffd-b50a-c1465fb4a0c1,2022/11/02,324.11,Electronics,PayPal
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023/01/18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024/02/13,431.64,Health & Beauty,Credit Card
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022/09/26,343.46,Health & Beauty,Debit Card

In [26]:
print(df_clean.loc[356])

CustomerID         3c0eae54-dde8-4291-95d3-f8dfb98c475a
TransactionID      ea7f4d30-45c8-4e24-8f37-c30527a1d6a3
TransactionDate                              2022/10/28
Amount                                           854.42
ProductCategory                             Electronics
PaymentMethod                               Credit Card
Name: 356, dtype: object

In [28]:
df_clean.isnull().sum()

CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

In [29]:
# Export the DataFrame to a CSV file

df_clean.to_csv('customer_transactions_cleaned.csv', index=False)

In [30]:
df_clean['PaymentMethod'].value_counts()

PaymentMethod
Debit Card       648
Credit Card      638
Bank Transfer    631
PayPal           612
Name: count, dtype: int64

In [31]:
df_clean['ProductCategory'].value_counts()

ProductCategory
Clothing           523
Electronics        518
Automotive         510
Home & Garden      491
Health & Beauty    487
Name: count, dtype: int64