In [1]:
# Import Pandas

import pandas as pd

In [2]:
#load Data set

df = pd.read_csv("social_media_interactions_contaminated.csv")

In [3]:
df

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN
...,...,...,...,...,...,...
3195,8d8fe8bd-2009-4a15-be37-83dba3cef447,2212803c-4a00-4263-bae5-aaaff6d6bdb1,2023-08-30,Instagram,Like,Neutral
3196,1756838b-8368-4852-b4a5-32a23643a3dd,2f50ca57-f930-4d3e-ae08-9f3b26c7f148,2024-06-16,Facebook,Like,Neutral
3197,eb8bb3ce-e182-4a9c-8084-c55c738815e1,ee2c3d14-248c-48b0-aa80-4ea97e449bf8,2023-12-22,Instagram,Comment,Negative
3198,a5d08a95-9dba-4e3d-b997-1cfdde6a89ef,e77a8713-fdc7-4f71-85f8-9cd88cca0c42,2023-11-01,Twitter,Share,Positive
3199,f8146100-569d-4cda-9d64-88c6ad98de5f,454a0b90-d1bb-437d-ad50-ef01821fbf0a,2024-06-20,Instagram,Like,Neutral

In [4]:
#Dropping duplicate rows

df = df.drop_duplicates()
df

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN
...,...,...,...,...,...,...
3166,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Neutral
3170,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,NaN,Like,Very Negative
3173,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,2023-12-16,Twitter,Like,Neutral
3175,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Negative
3194,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024-06-29,Twitter,Share,Negative

In [5]:
# checking for null 

df.isnull().sum()

CustomerID           0
InteractionID        0
InteractionDate      0
Platform           291
InteractionType      0
Sentiment          309
dtype: int64

In [6]:
#Dropping rows with null values in Platform column

df= df.dropna(subset=["Platform"])

In [7]:
#Dropping rows with null values in Sentiment column

df= df.dropna(subset=["Sentiment"])
df

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
5,3e44871b-f56c-4576-b1ca-d1dc999e2166,0c409883-8396-48e4-83fb-887329848696,2023-12-18,Instagram,Comment,Positive
6,aa5eea4b-c948-41f4-9285-229a470002aa,4034dadf-6541-40d6-a7f0-16b20a009c04,2023-11-15,Instagram,Share,Positive
10,481bcc62-9dcb-4766-bbdd-79f5554d73f8,785b7854-4548-4251-83f2-a25da78bfe40,2024-05-28,Twitter,Like,Positive
...,...,...,...,...,...,...
3146,ce2ece8f-91c3-420a-9d80-8b1f5051dc77,3a30bab5-53a0-4169-8244-419e2459dcd9,17/06/2024,Instagram,Share,Positive
3166,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Neutral
3173,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,2023-12-16,Twitter,Like,Neutral
3175,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Negative
3194,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024-06-29,Twitter,Share,Negative

In [8]:
# Standardize separators to slashes
s = df['InteractionDate'].astype(str).str.replace('-', '/')

# Create an empty series for the results
parsed_dates = pd.Series(pd.NaT, index=df.index)

# Group 1: Rows where the year is first (starts with 4 digits, e.g., 2026/...)
is_year_first = s.str.match(r'^\d{4}')
parsed_dates[is_year_first] = pd.to_datetime(s[is_year_first], errors='coerce')

# Group 2: Rows where the day is first (e.g., 31/12/2026)
is_day_first = ~is_year_first & s.notna()
parsed_dates[is_day_first] = pd.to_datetime(s[is_day_first], dayfirst=True, errors='coerce')

# Convert back to standard YYYY/MM/DD format string
df['InteractionDate'] = parsed_dates.dt.strftime('%Y/%m/%d')

In [9]:
df

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024/05/24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023/11/01,Instagram,Like,Neutral
5,3e44871b-f56c-4576-b1ca-d1dc999e2166,0c409883-8396-48e4-83fb-887329848696,2023/12/18,Instagram,Comment,Positive
6,aa5eea4b-c948-41f4-9285-229a470002aa,4034dadf-6541-40d6-a7f0-16b20a009c04,2023/11/15,Instagram,Share,Positive
10,481bcc62-9dcb-4766-bbdd-79f5554d73f8,785b7854-4548-4251-83f2-a25da78bfe40,2024/05/28,Twitter,Like,Positive
...,...,...,...,...,...,...
3146,ce2ece8f-91c3-420a-9d80-8b1f5051dc77,3a30bab5-53a0-4169-8244-419e2459dcd9,2024/06/17,Instagram,Share,Positive
3166,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024/04/30,Twitter,Share,Neutral
3173,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,2023/12/16,Twitter,Like,Neutral
3175,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024/01/28,Facebook,Share,Negative
3194,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024/06/29,Twitter,Share,Negative

In [13]:
df['Sentiment'].value_counts()

Sentiment
Positive         804
Neutral          797
Negative         789
Very Positive     29
Very Negative     28
Name: count, dtype: int64

In [14]:
df['Platform'].value_counts()

Platform
Instagram    836
Twitter      814
Facebook     797
Name: count, dtype: int64

In [15]:
df['InteractionType'].value_counts()

InteractionType
Share      821
Comment    820
Like       806
Name: count, dtype: int64

In [16]:
df.isnull().sum()

CustomerID         0
InteractionID      0
InteractionDate    0
Platform           0
InteractionType    0
Sentiment          0
dtype: int64

In [18]:
# Export the DataFrame to a CSV file
df.to_csv('social_media_interactions_cleaned.csv', index=False)