In [1]:
#Import Library

import pandas as pd

In [2]:
#Load data sets

df = pd.read_csv("customer_transactions_contaminated.csv")

In [3]:
#Load panda

df

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer
...,...,...,...,...,...,...
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3197,34e3f558-622e-4d6b-8d5d-07ab632e1b95,db0a4640-ea96-4fcd-989b-b71ba767529c,2022-12-26,NaN,Home & Garden,PayPal
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card
3199,d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9,6c47f481-3a5c-49bc-ab1d-2b198394b2e8,2023-06-20,NaN,Electronics,Debit Card

In [4]:
#Getting the sum of global duplicates

df.duplicated().sum()

np.int64(185)

In [5]:
#Info to get shape, null count, and dtypes

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   str
 1   TransactionID    3200 non-null   str
 2   TransactionDate  3200 non-null   str
 3   Amount           2896 non-null   str
 4   ProductCategory  2901 non-null   str
 5   PaymentMethod    3200 non-null   str
dtypes: str(6)
memory usage: 486.8 KB

In [6]:
#Dropping global duplicates

df = df.drop_duplicates()

df.shape

(3015, 6)

In [7]:
#Creating a variable for duplicated transaction

duplicates_transaction = df[df["TransactionID"].duplicated(keep=False)].sort_values("TransactionID")

duplicates_transaction

#Analysis: Double transactionID's were found but second transaction is either: free, cashback, 0, or NaN. 
#Recommendation: Keep both transactions, since

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal
413,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,953.86,Health & Beauty,PayPal
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal
431,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,30/07/2022,506.96,Automotive,Credit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
2081,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,504.42,Electronics,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
220,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,125.77,NaN,Bank Transfer
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
1093,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,764.92,Clothing,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
2371,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,05/04/2023,NaN,Home & Garden,Bank Transfer
3094,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,2023-02-04,NaN,Home & Garden,Bank Transfer
629,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,0,Electronics,Debit Card
3153,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,974.25,Electronics,Debit Card
2690,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,10/06/2024,591.61,Clothing,Debit Card
3048,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,2023-05-10,591.61,Clothing,Debit Card
283,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,2023-02-26,634.41,NaN,PayPal
3105,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,27/03/2024,634.41,NaN,PayPal
940,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-14,272.68,Clothing,Debit Card
3164,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,20/07/2022,272.68,Clothing,Debit Card
2610,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,766.97,Health & Beauty,Credit Card
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card
1639,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,446.84,Health & Beauty,Debit Card
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
807,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,2023-03-23,50.07,Automotive,Bank Transfer
3157,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,10/08/2022,50.07,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
3113,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,2024-03-05,252.7,Electronics,Debit Card

In [8]:
#Checking for the number of duplicated transaction in the TransactionID column

duplicates_transaction["TransactionID"].nunique()

15

In [9]:
#Removing 2 transaction with a specific transaction ID. Amount is NaN for both transation and have different dates, Better to remove rows than to imputate mean

df = df[df["TransactionID"] != "62186b07-9cda-44c5-bf76-bdb0f97aaf39"]

In [10]:
#Reloaded from the update above

duplicates_transaction = df[df["TransactionID"].duplicated(keep=False)].sort_values("TransactionID")

duplicates_transaction

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal
413,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,953.86,Health & Beauty,PayPal
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal
431,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,30/07/2022,506.96,Automotive,Credit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
2081,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,504.42,Electronics,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
220,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,125.77,NaN,Bank Transfer
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
1093,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,764.92,Clothing,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
629,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,0,Electronics,Debit Card
3153,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,974.25,Electronics,Debit Card
2690,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,10/06/2024,591.61,Clothing,Debit Card
3048,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,2023-05-10,591.61,Clothing,Debit Card
283,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,2023-02-26,634.41,NaN,PayPal
3105,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,27/03/2024,634.41,NaN,PayPal
940,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-14,272.68,Clothing,Debit Card
3164,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,20/07/2022,272.68,Clothing,Debit Card
2610,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,766.97,Health & Beauty,Credit Card
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card
1639,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,446.84,Health & Beauty,Debit Card
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
807,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,2023-03-23,50.07,Automotive,Bank Transfer
3157,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,10/08/2022,50.07,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
3113,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,2024-03-05,252.7,Electronics,Debit Card

In [11]:
#Checking if a pair of duplicate was removed.

duplicates_transaction["TransactionID"].nunique()

#Analysis: Since this transactions are paid transactions and cashback, It would be best to not remove the duplicated transaction ID

14

In [12]:
#Rechecking new shape of dataset

df.shape

(3013, 6)

In [13]:
df.isna().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             281
ProductCategory    282
PaymentMethod        0
dtype: int64

In [14]:
#Setting a standard date format of TransactionDate by making the datatype datetime

df["TransactionDate"] = pd.to_datetime(df["TransactionDate"], format="mixed", dayfirst=True, errors="coerce")

In [15]:
#Showing 20 random rows to double check the TransactionDate Format

df.sample(20)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
895,8f913b3f-65fa-4fff-b402-bff340ad86c8,e0c8f942-defb-4def-9ffe-ef8614773d7e,2023-09-14,714.51,Home & Garden,Bank Transfer
550,35dc485e-ab21-430b-87b0-b09dab982f99,14c5bd38-9a6f-4588-86d3-d209c98e08a0,2024-01-24,373.99,Clothing,Debit Card
180,23b9cd7f-aacb-46b4-b69c-72800cba3f39,69fb52a7-e66b-4183-bf13-d81d383aa153,2024-02-21,550.16,Electronics,Bank Transfer
2175,f6bbcdaa-e3ec-489a-9d20-b2599f57323e,99bc5357-46d7-459b-8632-3040c3687b4c,2023-05-08,748.47,Clothing,Debit Card
1970,c3a5e86e-a74b-420e-b1e7-13bcbe6b71ac,eb9e7afb-833a-4441-b5e8-c80e84016e92,2022-07-20,750.13,Automotive,PayPal
949,afc2cf41-aacb-482c-a3f0-2f68035c44f7,a6555708-c62b-4392-88fa-5dfa9216a1d3,2022-09-14,734.85,Automotive,Bank Transfer
1649,1662e025-dc0e-4ab0-8728-cb90e85bfdeb,8e7d2299-1217-4505-91ba-fff000d059cc,2023-03-07,36.21,Clothing,Debit Card
767,4090ba85-b111-4f75-a792-c777965f5255,04edc4fc-1565-4a82-af75-5b5caacaa9c4,2024-06-27,138.72,Home & Garden,Bank Transfer
1923,979c8237-bae7-4240-9224-b283bc02529e,0683f990-9984-4cd0-924a-0345067cd66e,2023-08-17,618.75,Home & Garden,Credit Card
1594,92ad692c-6e50-43bd-b47e-b0606ce6e802,49ba8708-9c37-4289-967f-ad1e782d7d48,2022-08-19,912.41,Home & Garden,Bank Transfer
1892,57d07b58-1c57-4f29-a180-459d7928dfc0,4c91e756-5e98-41ed-88e8-7aa3422a328a,2022-10-13,376.68,Home & Garden,PayPal
535,22c10765-8b8f-4765-af83-1924d41b84a0,a165c073-e844-40fa-8283-322e71cc8226,2024-01-05,28.04,Health & Beauty,Credit Card
81,e0f00c2f-f43d-424f-9c71-3fb0f3b02d6f,59d4388f-3c92-4150-a8dd-b253774ae8dd,2023-11-10,715.2,Electronics,PayPal
48,6ce19d4b-8794-4a6a-b479-6b46b786836b,fde080f4-b08d-4920-b29e-b7223c2aa907,2022-08-09,NaN,Health & Beauty,Bank Transfer
2451,7880b7a8-d348-4a4a-b939-6e6285a9d85c,3351b3d3-3e22-4b8b-af18-2cfeb3cf18ba,2024-12-02,181.65,Automotive,Credit Card
2974,32ac26c6-b07d-4ac9-b659-f36459af6337,e4221a5d-928b-4623-a209-6b1346a40947,2023-11-17,112.84,Health & Beauty,Debit Card
1411,f6bbcdaa-e3ec-489a-9d20-b2599f57323e,6f66f251-6a37-4662-9b70-1b17d9c11fbc,2022-07-19,970.74,Automotive,Bank Transfer
1461,1bdeb580-975a-42df-8248-fbb7d027d23e,6f4bbd7a-09d3-4aee-9f21-9cbdc7d92c0d,2024-02-28,797.61,Home & Garden,Debit Card
1471,ec58ff99-ede4-4b51-8b0c-efdbb61275a7,469184ef-d550-453f-966e-cda0f1e55347,2023-05-26,NaN,Health & Beauty,Debit Card
145,045ab4a7-5793-4f93-bb9a-8becd4e20422,ba13cafe-a210-46cc-bb60-9d2f84c6e7aa,2024-10-03,144.67,NaN,PayPal

In [16]:
#Checking for the unique values in "Amount" 
##Only the -100, free, and 0, are being analyzed at the moment

df["Amount"].value_counts()

Amount
-100      39
Free      30
0         29
54.66      2
175.31     2
          ..
993.24     1
309.7      1
206.5      1
252.7      1
974.25     1
Name: count, Length: 2603, dtype: int64

In [17]:
#Replacing the "Free" to 0 to make the values in "Amount" all numeric

df["Amount"] = df["Amount"].replace("Free", 0)

In [18]:
#Converting the dtype of Amount column to numeric

df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce")

In [19]:
#Checking new info for the data type

df.info()

<class 'pandas.DataFrame'>
Index: 3013 entries, 0 to 3177
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3013 non-null   str
 1   TransactionID    3013 non-null   str
 2   TransactionDate  3013 non-null   datetime64[us]
 3   Amount           2732 non-null   float64
 4   ProductCategory  2731 non-null   str
 5   PaymentMethod    3013 non-null   str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 437.7 KB

In [20]:
#Checking the statistical values of numerical columns with describe

df.describe()

                  TransactionDate       Amount
count                        3013  2732.000000
mean   2023-07-07 03:21:41.161633   484.410564
min           2022-01-07 00:00:00  -100.000000
25%           2023-01-05 00:00:00   219.450000
50%           2023-07-11 00:00:00   489.015000
75%           2024-01-19 00:00:00   745.030000
max           2024-12-06 00:00:00   999.860000
std                           NaN   301.938560

In [21]:
#Getting the mean and median with the amount using product category

df.groupby("ProductCategory")["Amount"].agg(["mean", "median" , "min", "max"])

#Analysis: All product category have the same min and almost similar max, the amount of difference in mean and median are also little
#Recommend: Still use the median for all and imputate missing values on the median of their respective product category

                       mean  median    min     max
ProductCategory
Automotive       491.930020  508.04 -100.0  999.86
Clothing         485.735667  491.62 -100.0  998.83
Electronics      478.159393  494.09 -100.0  999.86
Health & Beauty  467.054586  458.76 -100.0  999.56
Home & Garden    504.735597  511.64 -100.0  998.28

In [22]:
#Checking if there is a row that has null value in both amount and product category

df[df["Amount"].isna() & df["ProductCategory"].isna()]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
52,31a64c59-e32d-4d9c-ba9c-f308acd78daf,3db167d5-18aa-4073-a3fe-fb8971d83c6a,2023-08-20,NaN,NaN,Bank Transfer
254,f1f6626a-0ed5-4bc8-8a3a-511c3a1611fa,912daa90-8efc-486c-a4ce-e5f2407940ba,2022-10-13,NaN,NaN,PayPal
262,29b5dfdb-3011-4160-aec5-6761021f86e5,cf040478-b79e-4c3f-91ba-f6f40491edc1,2023-07-11,NaN,NaN,Bank Transfer
453,07f8f7be-d915-4e08-9c0d-250646b1c200,55e69849-389b-4cb8-8473-3434d70318e7,2023-02-05,NaN,NaN,Debit Card
704,6685f2fb-41e7-48e5-80d0-8da360b791f1,9da76e9d-3804-49f0-96b4-056217265890,2024-05-28,NaN,NaN,Bank Transfer
837,ecb9513f-fa9d-432c-996e-87fb80dc8827,bad309a4-afe9-450d-bcc5-0155b2ce7d1c,2023-03-25,NaN,NaN,Debit Card
993,d160e8f2-113e-4e69-928c-b6303f391203,27f22f16-463b-415f-8e5c-09db81e2c468,2023-05-19,NaN,NaN,Debit Card
1102,c288b8e0-209a-408b-8135-28f8e81b053b,c5fe314d-d0ea-42b2-923e-36d9a0d44595,2022-10-13,NaN,NaN,Debit Card
1178,f3607f0a-e99d-435a-8f43-6060f5f03735,28fe80d5-0425-4952-a3a8-2d3973240b87,2023-03-23,NaN,NaN,Bank Transfer
1199,9e48e3cd-839b-46a1-ae48-b47c006073da,a2cbe1bb-22d9-4c68-acff-e9891048873c,2024-09-03,NaN,NaN,PayPal
1227,72e6f859-2111-4be3-b0e1-53895f0760bf,bfab64ba-ea96-4d36-964a-7d1416a52f64,2023-12-15,NaN,NaN,PayPal
1308,b8a3bca9-79e2-4a99-96be-f23108c05f00,be1dbbf5-ef73-4d2f-a4ac-7745a8ce62d6,2022-04-09,NaN,NaN,Bank Transfer
1363,efa73de0-f044-49ae-8118-c5607b420e4c,7b67fccd-0a58-4de3-a567-44d1c907c677,2023-10-03,NaN,NaN,PayPal
1701,8d8fe8bd-2009-4a15-be37-83dba3cef447,4662112b-36ea-4f6d-84d2-365dd6605280,2024-08-03,NaN,NaN,PayPal
1782,e173b550-09e9-4e41-a7a6-ed62238a5435,c8865a23-9c7c-4210-ba71-e224f5d128ca,2022-11-25,NaN,NaN,Debit Card
2029,28c29c18-0cbe-40ea-b218-a96430cc4409,1c2f49aa-1e1c-4ada-b021-699f68190652,2023-10-19,NaN,NaN,PayPal
2041,fb14afde-4087-42b4-9010-ad71aa367602,29784dd5-1bda-4978-a38c-b6d462072211,2023-08-04,NaN,NaN,Credit Card
2160,1fac8ad1-9a12-4370-bb35-5e1aa8b3419e,38b62386-5783-4520-8633-80787f1f5173,2023-09-09,NaN,NaN,Bank Transfer
2237,b03edff3-4a64-4e5e-8818-10e37291a8c6,1e9ca466-bb1c-4c89-a316-2ec951a72545,2023-03-05,NaN,NaN,Credit Card
2313,42f52b1e-bedb-4294-8039-7b08c1be1662,c6afc640-8f7d-4b89-917f-36956fcce576,2023-12-20,NaN,NaN,Bank Transfer
2374,2dc4607e-012f-42ce-bcbe-2508d828cf4c,71545c6d-1808-4ef7-89ad-be6b387b180f,2024-06-05,NaN,NaN,PayPal
2448,451f473d-4ebe-4919-9e21-4fd1b45d65be,240cce17-e93f-4ad2-bee0-12a5545053e5,2024-04-04,NaN,NaN,PayPal
2492,0c68dabb-b818-43bf-96de-e0b384ace943,fd709794-8a12-4217-b2af-4113b123b088,2024-05-26,NaN,NaN,Credit Card
2640,095992d4-56e4-4756-b930-74f701363489,d4c76f11-434d-4eeb-a845-d41a7e1bc077,2024-02-26,NaN,NaN,PayPal
2797,6534afd4-bd7d-4e8c-a2e2-2986fc764bed,eed391dd-9805-4afd-99d9-cc3dd538fb7f,2024-03-22,NaN,NaN,Debit Card
2881,d968cee0-3524-42d4-a0f7-5fe6e8284890,e2273516-8218-40e5-bf53-2754a6a5e980,2024-09-03,NaN,NaN,Credit Card

In [23]:
#Checking the sum of rows that have null amount and null in product category 

(df["Amount"].isna() & df["ProductCategory"].isna()).sum()

#Analysis: transactions are shown with null amount and null product categories
#Recommend: Best to remove this rows since this is specifically a transaction csv/

np.int64(26)

In [24]:
#Checking shape before dropping rows

df.shape

(3013, 6)

In [25]:
#Dropping rows that have null values in both amount and productcategory

df = df[~(df["Amount"].isna() & df["ProductCategory"].isna())]

df.shape

#Analysis: 3013 - 26 rows = 2987, only 26 rows were removed.

(2987, 6)

In [26]:
#Checking if there are still rows with both amount and productcategory null

df[df["Amount"].isna() & df["ProductCategory"].isna()]

#Analysis: 0 rows were found

Empty DataFrame
Columns: [CustomerID, TransactionID, TransactionDate, Amount, ProductCategory, PaymentMethod]
Index: []

In [27]:
#Checking the sum of null values in Amount

df["Amount"].isna().sum()

np.int64(255)

In [28]:
#Creating a median variable for each Product Category

automotive_median = df[df["ProductCategory"] == "Automotive"]["Amount"].median()
clothing_median = df[df["ProductCategory"] == "Clothing"]["Amount"].median()
electronics_median = df[df["ProductCategory"] == "Electronics"]["Amount"].median()
health_beauty_median = df[df["ProductCategory"] == "Health & Beauty"]["Amount"].median()
home_garden_median = df[df["ProductCategory"] == "Home & Garden"]["Amount"].median()


print("Median of Product Categories")
print("The median for Automotive is: ", automotive_median)
print("The median for Clothing is: ", clothing_median)
print("The median for Electronics is: ", electronics_median)
print("The median for Health & Beauty is: ", health_beauty_median)
print("The median for Home & Garden is: ", home_garden_median)

Median of Product Categories
The median for Automotive is:  508.04
The median for Clothing is:  491.62
The median for Electronics is:  494.09
The median for Health & Beauty is:  458.76
The median for Home & Garden is:  511.64

In [29]:
#Imputing null values of Amount with the mean of their corresponding Product Category

df.loc[df["ProductCategory"] == "Automotive", "Amount"] = df.loc[df["ProductCategory"] == "Automotive", "Amount"].fillna(automotive_median)
df.loc[df["ProductCategory"] == "Clothing", "Amount"] = df.loc[df["ProductCategory"] == "Clothing", "Amount"].fillna(clothing_median)
df.loc[df["ProductCategory"] == "Electronics", "Amount"] = df.loc[df["ProductCategory"] == "Electronics", "Amount"].fillna(electronics_median)
df.loc[df["ProductCategory"] == "Health & Beauty", "Amount"] = df.loc[df["ProductCategory"] == "Health & Beauty", "Amount"].fillna(health_beauty_median)
df.loc[df["ProductCategory"] == "Home & Garden", "Amount"] = df.loc[df["ProductCategory"] == "Home & Garden", "Amount"].fillna(home_garden_median)

#checking the sum of null values after imputing
df["Amount"].isna().sum()

np.int64(0)

In [30]:
df["ProductCategory"].isna().sum()

np.int64(256)

In [31]:
df["ProductCategory"].value_counts()

ProductCategory
Clothing           571
Electronics        564
Automotive         540
Health & Beauty    528
Home & Garden      528
Name: count, dtype: int64

In [32]:
df.describe()

                  TransactionDate       Amount
count                        2987  2987.000000
mean   2023-07-06 12:06:30.492132   484.993663
min           2022-01-07 00:00:00  -100.000000
25%           2023-01-05 00:00:00   240.955000
50%           2023-07-10 00:00:00   494.090000
75%           2024-01-19 00:00:00   722.520000
max           2024-12-06 00:00:00   999.860000
std                           NaN   288.817917

In [33]:
#Checking corelation with ProductCategory and PaymentMethod

df.groupby("ProductCategory")["PaymentMethod"].value_counts().sort_values

#Analysis, there is not hard evidence of the connection of a payment method to a specific product category
#Analysis 2: Since there are 256 row of missing values, imputing the mode would push 1 product category above others
#Recommend: Fill all the null values with new category "Unspecified" to avoid skewing the data

<bound method Series.sort_values of ProductCategory  PaymentMethod
Automotive       PayPal           151
                 Credit Card      132
                 Bank Transfer    129
                 Debit Card       128
Clothing         Debit Card       154
                 Credit Card      149
                 Bank Transfer    139
                 PayPal           129
Electronics      Debit Card       157
                 Bank Transfer    140
                 PayPal           135
                 Credit Card      132
Health & Beauty  Credit Card      148
                 PayPal           130
                 Bank Transfer    126
                 Debit Card       124
Home & Garden    Debit Card       144
                 Bank Transfer    140
                 Credit Card      125
                 PayPal           119
Name: count, dtype: int64>

In [34]:
#Filling null values in ProductCategory as Unspecified

df["ProductCategory"] = df["ProductCategory"].fillna("Unspecified")

In [35]:
df.info()

<class 'pandas.DataFrame'>
Index: 2987 entries, 0 to 3177
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       2987 non-null   str
 1   TransactionID    2987 non-null   str
 2   TransactionDate  2987 non-null   datetime64[us]
 3   Amount           2987 non-null   float64
 4   ProductCategory  2987 non-null   str
 5   PaymentMethod    2987 non-null   str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 436.6 KB

In [36]:
df.isna().sum()

CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

In [37]:
#Sorting the global data to transaction date

df = df.sort_values("TransactionDate")

df

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
523,1a8a0568-f287-49ae-b1e0-3bbba67c15b0,42a61ca2-c5d3-41be-946a-84fd42891492,2022-01-07,254.64,Home & Garden,Debit Card
1049,404f9aca-5c0b-484f-a4ec-65ef1b401718,38d5af45-0409-4d32-8dd9-87265f4aba52,2022-01-07,18.45,Unspecified,Debit Card
1069,576fc0ef-5017-4d85-ba43-136e65f10a7f,860d6e54-0366-424d-9df1-3ea96b03f207,2022-01-07,699.34,Unspecified,Bank Transfer
906,1ccb71e6-8f53-423f-808d-a2023aa0c5a8,e4105300-4326-4494-8ecc-267319351d56,2022-01-07,377.09,Home & Garden,Bank Transfer
328,c448b2f5-80a5-4fde-8144-8bea32bc3618,16c90584-1b6f-4d6e-ba22-32407b163757,2022-01-07,983.83,Health & Beauty,Credit Card
...,...,...,...,...,...,...
1173,c6f3aa4e-9147-4547-b2c9-b1aa7847d304,e4cd88dc-9f64-4c2c-91af-ae18651f4b32,2024-12-05,511.64,Home & Garden,PayPal
164,c6460a4f-0c2d-47b7-82ce-2600e5232a41,9293a358-a2ce-4aa2-b082-5a59088e5980,2024-12-05,52.78,Automotive,Bank Transfer
1427,f447245d-7239-4808-974c-7fd358f61c2c,0418b214-ef64-4eec-bbe7-f0a3008ddf83,2024-12-05,244.05,Automotive,Debit Card
994,0a5270eb-ff97-4072-a9f0-2203be2469a4,c6cb82ba-cc14-425e-83da-7a5cd1064c26,2024-12-05,93.84,Unspecified,PayPal
2299,1d29565d-2123-4b85-b499-92a928a5fd2e,e39d91fa-5b7f-4358-8df2-7325fece2a10,2024-12-06,71.87,Automotive,PayPal

In [38]:
#Resetting the row number

df_clean = df.reset_index(drop=True)

df_clean

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,1a8a0568-f287-49ae-b1e0-3bbba67c15b0,42a61ca2-c5d3-41be-946a-84fd42891492,2022-01-07,254.64,Home & Garden,Debit Card
1,404f9aca-5c0b-484f-a4ec-65ef1b401718,38d5af45-0409-4d32-8dd9-87265f4aba52,2022-01-07,18.45,Unspecified,Debit Card
2,576fc0ef-5017-4d85-ba43-136e65f10a7f,860d6e54-0366-424d-9df1-3ea96b03f207,2022-01-07,699.34,Unspecified,Bank Transfer
3,1ccb71e6-8f53-423f-808d-a2023aa0c5a8,e4105300-4326-4494-8ecc-267319351d56,2022-01-07,377.09,Home & Garden,Bank Transfer
4,c448b2f5-80a5-4fde-8144-8bea32bc3618,16c90584-1b6f-4d6e-ba22-32407b163757,2022-01-07,983.83,Health & Beauty,Credit Card
...,...,...,...,...,...,...
2982,c6f3aa4e-9147-4547-b2c9-b1aa7847d304,e4cd88dc-9f64-4c2c-91af-ae18651f4b32,2024-12-05,511.64,Home & Garden,PayPal
2983,c6460a4f-0c2d-47b7-82ce-2600e5232a41,9293a358-a2ce-4aa2-b082-5a59088e5980,2024-12-05,52.78,Automotive,Bank Transfer
2984,f447245d-7239-4808-974c-7fd358f61c2c,0418b214-ef64-4eec-bbe7-f0a3008ddf83,2024-12-05,244.05,Automotive,Debit Card
2985,0a5270eb-ff97-4072-a9f0-2203be2469a4,c6cb82ba-cc14-425e-83da-7a5cd1064c26,2024-12-05,93.84,Unspecified,PayPal
2986,1d29565d-2123-4b85-b499-92a928a5fd2e,e39d91fa-5b7f-4358-8df2-7325fece2a10,2024-12-06,71.87,Automotive,PayPal

In [39]:
#FINAL CHECKS FOR THE CLEANED DATA SET

In [40]:
df_clean.shape

#Observation: Minimal rows were dropped from the original dataset

(2987, 6)

In [41]:
df_clean.info()

#Observation: Correct Datatypes, no null values

<class 'pandas.DataFrame'>
RangeIndex: 2987 entries, 0 to 2986
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       2987 non-null   str
 1   TransactionID    2987 non-null   str
 2   TransactionDate  2987 non-null   datetime64[us]
 3   Amount           2987 non-null   float64
 4   ProductCategory  2987 non-null   str
 5   PaymentMethod    2987 non-null   str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 413.8 KB

In [42]:
df_clean.duplicated().sum()

#Observation: No duplicated values in cleaned dataset

np.int64(0)

In [43]:
df_clean["TransactionID"].duplicated().sum()

#Observation: 14 transaction ID were identified and was double check to be a paid transaction + free product / cashback

np.int64(14)

In [44]:
df_clean["Amount"].describe()

#Observation: Minimal changes were made when imputed values were added.

count    2987.000000
mean      484.993663
std       288.817917
min      -100.000000
25%       240.955000
50%       494.090000
75%       722.520000
max       999.860000
Name: Amount, dtype: float64

In [45]:
df_clean["ProductCategory"].value_counts()

#Observation: Confirm only 5 original categories + added Unspecified
#Analysis: Product categories are well distributed with no specific category far above and far below the others

ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      528
Health & Beauty    528
Unspecified        256
Name: count, dtype: int64

In [46]:
df_clean["PaymentMethod"].value_counts()

#Observation: Only 4 Payment method were observed
#Analysis: All Payment method are close to each other

PaymentMethod
Debit Card       761
Credit Card      751
PayPal           741
Bank Transfer    734
Name: count, dtype: int64

In [47]:
#View 25 random rows 

df_clean.sample(25)

#Observation: No visible outliers in the sample provided.

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
2748,2daa9ac8-d5fc-48ea-b380-528bef681cef,e9521230-4b6d-49b1-a4bc-52ce13cc9d5c,2024-06-01,531.72,Health & Beauty,Debit Card
860,3fc8273c-1793-422e-b1b7-4f1217622e5c,1932e038-4ecd-4bf0-968a-e0055fde0c25,2023-01-30,623.72,Automotive,Debit Card
1973,e2b61ce8-65cb-437f-a370-4feef6395a80,96be372f-b8d0-4cdd-a394-772b08269e37,2023-11-03,491.62,Clothing,Credit Card
196,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-20,272.68,Clothing,Debit Card
2884,f3944eae-0876-467a-94ce-5c3b9813b454,a6d4e31e-624c-4f85-b342-525105ca7910,2024-08-03,342.12,Clothing,Credit Card
385,f8146100-569d-4cda-9d64-88c6ad98de5f,5b2a0ef6-b57b-4fb9-9965-e571ed81d881,2022-09-15,339.65,Clothing,Debit Card
1871,ce5437b0-66af-47b2-aa68-423d3b15685d,1ba3041e-8654-4d70-b9ab-657890251cb0,2023-10-11,31.21,Clothing,Debit Card
1489,143a7859-5fd2-4331-b520-ffb140afa5bd,e2311c7a-4b91-4da8-b90e-33b7cf71c0b2,2023-07-09,645.14,Clothing,Credit Card
1746,6c0120b7-486d-460e-b11e-6c8b6dc4770a,6ba4c6a4-30da-45e4-9805-8c234d38926f,2023-09-11,843.71,Health & Beauty,PayPal
1958,723f4d63-3160-48f6-86f9-768674ceb42f,62a92a1a-45d2-4641-860c-fee6a3b2d860,2023-10-30,559.69,Home & Garden,Bank Transfer
1983,948ad644-2c83-4eb1-af0c-c16e76afccfb,3594c1e5-d3f9-4c73-8f01-a7675b883f87,2023-11-06,686.25,Automotive,Bank Transfer
2416,270506ea-c72f-4926-a9f4-e29ea53adb9f,52d20d0c-4375-42c9-9396-159633ead703,2024-03-02,546.70,Home & Garden,PayPal
2195,b803eb0b-f143-44c2-b04e-547eb67c4a08,9963c3c8-c33c-4b4d-9604-717b48023863,2024-01-01,646.42,Automotive,PayPal
2737,9560ed71-7a04-4cd9-a576-b622c5690487,ad529898-c1b5-4fe7-b30b-a9f19c666386,2024-05-31,833.48,Automotive,Bank Transfer
79,56058449-276a-417e-b6c6-f8853b1d2659,cf682587-8173-4d23-95d2-89524fb1f308,2022-04-07,305.75,Health & Beauty,Debit Card
2159,3b50d972-3484-45ed-9168-99f2767cfffe,45b6db6c-a0ae-48d4-bcd6-55349cb424da,2023-12-24,236.13,Clothing,Credit Card
2825,3a204a5c-66e7-44fe-b1b7-6ca40fb677b5,2c8a0375-34eb-4d08-a272-8b449884ef60,2024-06-27,816.68,Electronics,Debit Card
1897,62e3a7aa-cc76-4c4f-9e65-9aea8f238f22,895114c5-2f68-4b30-a5a2-1619c8cfccc3,2023-10-15,508.04,Automotive,Debit Card
2335,2c35e69c-7e26-46cb-b2fc-02875830b4ab,148651bd-c139-4b61-b2a3-d7f8381451d1,2024-02-15,39.76,Clothing,Bank Transfer
2402,1bdeb580-975a-42df-8248-fbb7d027d23e,6f4bbd7a-09d3-4aee-9f21-9cbdc7d92c0d,2024-02-28,797.61,Home & Garden,Debit Card
997,70b70bf3-205e-4992-a88c-02bf2ed1471f,a35f514f-eea3-4f3b-8570-54382031a9d9,2023-03-11,746.60,Clothing,Bank Transfer
1715,429afb4b-99cc-4a38-8f43-9187a3e02ecc,ca2a3621-1db6-4b0a-b2b5-184412b31a5e,2023-09-03,993.14,Health & Beauty,PayPal
969,ec5770ea-d47e-4872-8e74-3c77c1fe8b3c,2400769e-174e-4c0e-9d49-8fb14273840d,2023-03-03,461.04,Unspecified,Credit Card
2336,32ae4542-77b0-4a2c-90c9-63b08e717945,32b12015-6d84-47f3-8111-89aa17ed6941,2024-02-15,941.88,Home & Garden,Credit Card
438,a319acae-e640-4d21-8215-b5b0eac9c64b,b2f7566e-b9fe-471c-9806-7b51483c864f,2022-09-28,746.63,Clothing,PayPal

In [119]:
df_clean.to_csv("Customer_Transactions_Cleaned.csv" , index=False)

In [49]:
amount_mode = df_clean["Amount"].mode()[0]
amount_range = df_clean["Amount"].max() - df_clean["Amount"].min()
amount_variance = df_clean["Amount"].var()
amount_std = df_clean["Amount"].std()

print("Mode:", amount_mode)
print("Range:", amount_range)
print("Variance:", amount_variance)
print("Standard Deviation:", amount_std)

Mode: 0.0
Range: 1099.8600000000001
Variance: 83415.78934900598
Standard Deviation: 288.8179172922033

In [50]:
df_clean["Amount"].describe()

count    2987.000000
mean      484.993663
std       288.817917
min      -100.000000
25%       240.955000
50%       494.090000
75%       722.520000
max       999.860000
Name: Amount, dtype: float64

In [55]:
#Creating a table for Descriptive statistics with 0 and -100 amount transactions removed

amount_clean = df_clean[(df_clean["Amount"] != 0) & (df_clean["Amount"] != -100)]["Amount"]

# EDA 
print(f"Mean: ₱{amount_clean.mean():.2f}")
print(f"Median: ₱{amount_clean.median():.2f}")
print(f"Mode: ₱{amount_clean.mode()[0]:.2f}")
print(f"Min: ₱{amount_clean.min():.2f}")
print(f"Max: ₱{amount_clean.max():.2f}")
print(f"Range: ₱{amount_clean.max() - amount_clean.min():.2f}")
print(f"Variance: {amount_clean.var():.2f}")
print(f"Standard Deviation: ₱{amount_clean.std():.2f}")
print(f"25%: ₱{amount_clean.quantile(0.25):.2f}")
print(f"50%: ₱{amount_clean.quantile(0.50):.2f}")
print(f"75%: ₱{amount_clean.quantile(0.75):.2f}")

Mean: ₱503.18
Median: ₱496.26
Mode: ₱458.76
Min: ₱10.03
Max: ₱999.86
Range: ₱989.83
Variance: 76342.00
Standard Deviation: ₱276.30
25%: ₱269.50
50%: ₱496.26
75%: ₱731.75

In [56]:
print("\n\n=== Customer Transactions ===")

print("\nProduct Category:")
print(df_clean["ProductCategory"].value_counts())

print("\nPayment Method:")
print(df_clean["PaymentMethod"].value_counts())

=== Customer Transactions ===

Product Category:
ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      528
Health & Beauty    528
Unspecified        256
Name: count, dtype: int64

Payment Method:
PaymentMethod
Debit Card       761
Credit Card      751
PayPal           741
Bank Transfer    734
Name: count, dtype: int64