In [1]:
#Import library

import pandas as pd

In [2]:
#Load Datasets

df = pd.read_csv("customer_demographics_contaminated.csv")

In [3]:
#print the panda df

df

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24
...,...,...,...,...,...,...
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17
3196,0ef84cc6-0b4c-4c56-bdaa-d6b725ccc08e,40.0,Male,Lisaside,Medium,2022-07-23
3197,0ede97d1-bb46-452d-893e-b63f37da4fa8,NaN,Female,North Christinaport,High,2021-10-16
3198,43ec68f5-4305-4b40-8ced-a187d00bb3f5,26.0,Female,Carrilloport,Low,2022-09-26
3199,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09

In [4]:
#Checking df info (Dtypes, null. values, column names)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   3200 non-null   str
 1   Age          2909 non-null   str
 2   Gender       3200 non-null   str
 3   Location     3200 non-null   str
 4   IncomeLevel  2897 non-null   str
 5   SignupDate   3200 non-null   str
dtypes: str(6)
memory usage: 371.6 KB

In [5]:
#Checking for duplicated rows

df.duplicated().value_counts()

False    3023
True      177
Name: count, dtype: int64

In [6]:
#Checking for duplicates in Customer ID. 

print("Duplicate CustomerIDs:", df["CustomerID"].duplicated().sum())

Duplicate CustomerIDs: 200

In [7]:
#Creating a duplicate variable to check the duplicates in customerID

duplicates = df[df["CustomerID"].duplicated(keep=False)]
print(duplicates.sort_values("CustomerID"))

#EDA: Possible minor formatting difference but since it has the same customer ID, recommend to combine into 1 to avoid customer details repeat

                                CustomerID   Age  Gender         Location  \
2559  0047d8ce-a5bb-4db7-860f-6ff66e1cd060  40.0    Male     Mitchellview
3039  0047d8ce-a5bb-4db7-860f-6ff66e1cd060  40.0    Male     Mitchellview
1511  05609335-a647-4691-80a8-82b43518b767  52.0    Male        Jonesside
3169  05609335-a647-4691-80a8-82b43518b767  52.0    Male        Jonesside
1105  06af0246-5f53-45f4-997e-bf42706b11d7  53.0    Male       Stevenberg
...                                    ...   ...     ...              ...
3113  fd35b6b4-ad1c-49cc-9c34-8c2d696f38e2  42.0    Male        Karenbury
23    fd63f236-3ec3-401d-9fa1-53bda0bd7c0e   NaN    Male       Thomasbury
3148  fd63f236-3ec3-401d-9fa1-53bda0bd7c0e   NaN    Male       Thomasbury
165   fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f  59.0  Female  East Nathantown
3011  fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f  59.0  Female  East Nathantown

     IncomeLevel  SignupDate
2559      Medium  2021-11-11
3039      Medium  2021-11-11
1511         Low  2023-10-07
3169         Low  2023-10-07
1105         NaN  2022-11-25
...          ...         ...
3113         Low  2024-04-14
23           Low  2021-05-29
3148         Low  2021-05-29
165         High  2022-04-14
3011        High  2022-04-14

[400 rows x 6 columns]

In [8]:
#printing a table for duplicated CustomerID that is unique per column

print(duplicates.groupby("CustomerID").nunique())

                                      Age  Gender  Location  IncomeLevel  \
CustomerID
0047d8ce-a5bb-4db7-860f-6ff66e1cd060    1       1         1            1
05609335-a647-4691-80a8-82b43518b767    1       1         1            1
06af0246-5f53-45f4-997e-bf42706b11d7    1       1         1            0
077936e6-6556-434f-9494-e5d671b6e71c    1       1         1            1
08995799-8d0f-40d6-986b-452074709b5f    1       1         1            1
...                                   ...     ...       ...          ...
fa4c97fc-4a9f-4857-969e-ea9528b2792e    1       1         1            0
fc9f91cc-00f1-4ffa-8016-878c069f3a1b    1       1         1            1
fd35b6b4-ad1c-49cc-9c34-8c2d696f38e2    1       1         1            1
fd63f236-3ec3-401d-9fa1-53bda0bd7c0e    0       1         1            1
fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f    1       1         1            1

                                      SignupDate
CustomerID
0047d8ce-a5bb-4db7-860f-6ff66e1cd060           1
05609335-a647-4691-80a8-82b43518b767           1
06af0246-5f53-45f4-997e-bf42706b11d7           1
077936e6-6556-434f-9494-e5d671b6e71c           1
08995799-8d0f-40d6-986b-452074709b5f           2
...                                          ...
fa4c97fc-4a9f-4857-969e-ea9528b2792e           1
fc9f91cc-00f1-4ffa-8016-878c069f3a1b           1
fd35b6b4-ad1c-49cc-9c34-8c2d696f38e2           1
fd63f236-3ec3-401d-9fa1-53bda0bd7c0e           1
fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f           1

[200 rows x 5 columns]

In [9]:
#Creating a conflicts variable to check if there is a duplicated that is not unique (not 1)

conflicts_CustomerID = duplicates.groupby("CustomerID").nunique()

conflicts_CustomerID = conflicts_CustomerID[(conflicts_CustomerID != 1).any(axis=1)]

print(conflicts_CustomerID)

                                      Age  Gender  Location  IncomeLevel  \
CustomerID
06af0246-5f53-45f4-997e-bf42706b11d7    1       1         1            0
08995799-8d0f-40d6-986b-452074709b5f    1       1         1            1
0ab0e741-f4ad-4d82-92c4-b5055b5c5549    1       1         1            0
0d2cf4cd-88a9-4d71-8ed7-0f70b450e4d2    0       1         1            1
0ede97d1-bb46-452d-893e-b63f37da4fa8    0       1         1            1
1c4c3ec8-256e-4c2c-bed6-cf5e97e076de    0       1         1            1
1d26a8ed-88ca-4806-9ec1-7db7ee6a748f    1       1         1            0
1e9e7dcb-e612-46d3-bae6-0c2f47fa0220    1       1         1            1
22edbbf4-1eb5-4809-bf75-96d82a60bfb7    1       1         1            0
29436bcf-d6f8-44d1-a856-0794abb562ab    1       1         1            1
29bce3fc-ae36-42db-88d0-d9a87542acfa    1       1         1            0
2cd16dfc-d7b0-47ec-9999-b018daea7f8d    2       1         1            1
3814b8e4-cade-4665-86af-dda3e3628f17    2       1         1            1
390a3450-55ec-4a17-9a9b-02293e2b4c68    0       1         1            1
3e6a326a-f09b-47a2-8d24-3f69ac0a119c    0       1         1            1
40f5a5dd-a46f-4a5e-8c0f-fe04389ddec8    0       1         1            1
48313b18-ccdb-4946-b958-1ebfc92dcc2a    2       1         1            1
50465bde-6a9a-466d-804a-a8f046809a23    2       1         1            1
5050eefe-2392-4d18-b4b6-913d42b9f62b    2       1         1            1
518fa595-22b9-469c-8e3c-96cbfbb41ce7    1       1         1            0
544dda6b-7d2f-445c-90d9-caeccac0e548    1       1         1            0
6b2f8f03-ab9e-48a6-a07e-10e794b04fe0    2       1         1            1
6b63bf58-e948-4fc5-aa41-727f7c044c97    0       1         1            1
7120aefc-7d84-4981-b4ec-64e036fba72a    1       1         1            0
7544489f-ec7e-48af-bec6-b6eab94a6e5c    2       1         1            1
76c1d696-0f1c-44b5-b749-8859545658eb    2       1         1            1
7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc    1       1         1            1
83355281-fda3-4776-9f9d-a812243c3b56    1       1         1            1
835384f5-c976-481d-8961-cc827dc62c6b    1       1         1            1
890f10ce-36f6-4993-9a2e-a00dfdf01609    1       1         1            1
89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2    1       1         1            1
9612ee49-09dd-4f55-9524-9eb341efa2b9    2       1         1            1
9801b85b-036d-4425-891d-d45551a571d5    0       1         1            1
a0a6e4bc-9637-42b4-875a-7ccc6ebf3b04    1       1         1            0
b22ea045-5ad5-47fd-a03a-6657307f82bf    0       1         1            1
b3dd8e85-02ff-4345-b148-e76de51adf54    0       1         1            1
b72f2a59-aab0-447d-bb31-9bdc1405cc72    1       1         1            1
b8769321-aa3b-4684-941d-819a58caad05    1       1         1            0
bb07fa4a-8680-4b77-b1ad-5d2f67570252    1       1         1            1
bbe76a26-234f-4a70-b71f-fa9b183f6353    2       1         1            1
bbf7c36f-3745-4d3a-9e33-f927c2755f65    1       1         1            1
c2351d11-59fe-4630-a6df-e01bc343de33    1       1         1            0
c3f22991-8910-4823-86e4-8637520d3952    0       1         1            0
c5440e19-6474-40f0-9306-f4d590035241    1       1         1            0
c6747843-6a62-45f4-9cc6-c9cd85a67a81    1       1         1            0
ce5cf079-859b-43fa-9609-c6bb7e12c6b7    2       1         1            1
df49d870-e940-4a8d-9c68-4cef4e28d916    1       1         1            0
e2df0721-50dd-4f08-8f6b-ab18a0c51b85    1       1         1            0
ec42fc84-51a4-4f32-971a-132852d4fe36    0       1         1            1
ee0d17b8-9535-40ee-985e-8c733c34ca3f    1       1         1            0
f447245d-7239-4808-974c-7fd358f61c2c    0       1         1            1
f5a1c5be-8d36-4fb6-aba2-ba5a2751d3d4    0       1         1            1
f6db05bc-e9ff-454c-983c-fc4a7fd13323    1       1         1            0
fa4c97fc-4a9f-4857-969e-ea9528b2792e    1       1         1            0
fd63f236-3ec3-401d-9fa1-53bda0bd7c0e    0       1         1            1

                                      SignupDate
CustomerID
06af0246-5f53-45f4-997e-bf42706b11d7           1
08995799-8d0f-40d6-986b-452074709b5f           2
0ab0e741-f4ad-4d82-92c4-b5055b5c5549           1
0d2cf4cd-88a9-4d71-8ed7-0f70b450e4d2           1
0ede97d1-bb46-452d-893e-b63f37da4fa8           1
1c4c3ec8-256e-4c2c-bed6-cf5e97e076de           1
1d26a8ed-88ca-4806-9ec1-7db7ee6a748f           1
1e9e7dcb-e612-46d3-bae6-0c2f47fa0220           2
22edbbf4-1eb5-4809-bf75-96d82a60bfb7           1
29436bcf-d6f8-44d1-a856-0794abb562ab           2
29bce3fc-ae36-42db-88d0-d9a87542acfa           1
2cd16dfc-d7b0-47ec-9999-b018daea7f8d           1
3814b8e4-cade-4665-86af-dda3e3628f17           1
390a3450-55ec-4a17-9a9b-02293e2b4c68           1
3e6a326a-f09b-47a2-8d24-3f69ac0a119c           1
40f5a5dd-a46f-4a5e-8c0f-fe04389ddec8           1
48313b18-ccdb-4946-b958-1ebfc92dcc2a           1
50465bde-6a9a-466d-804a-a8f046809a23           1
5050eefe-2392-4d18-b4b6-913d42b9f62b           1
518fa595-22b9-469c-8e3c-96cbfbb41ce7           1
544dda6b-7d2f-445c-90d9-caeccac0e548           1
6b2f8f03-ab9e-48a6-a07e-10e794b04fe0           1
6b63bf58-e948-4fc5-aa41-727f7c044c97           1
7120aefc-7d84-4981-b4ec-64e036fba72a           1
7544489f-ec7e-48af-bec6-b6eab94a6e5c           1
76c1d696-0f1c-44b5-b749-8859545658eb           1
7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc           2
83355281-fda3-4776-9f9d-a812243c3b56           2
835384f5-c976-481d-8961-cc827dc62c6b           2
890f10ce-36f6-4993-9a2e-a00dfdf01609           2
89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2           2
9612ee49-09dd-4f55-9524-9eb341efa2b9           1
9801b85b-036d-4425-891d-d45551a571d5           1
a0a6e4bc-9637-42b4-875a-7ccc6ebf3b04           1
b22ea045-5ad5-47fd-a03a-6657307f82bf           1
b3dd8e85-02ff-4345-b148-e76de51adf54           1
b72f2a59-aab0-447d-bb31-9bdc1405cc72           2
b8769321-aa3b-4684-941d-819a58caad05           1
bb07fa4a-8680-4b77-b1ad-5d2f67570252           2
bbe76a26-234f-4a70-b71f-fa9b183f6353           1
bbf7c36f-3745-4d3a-9e33-f927c2755f65           2
c2351d11-59fe-4630-a6df-e01bc343de33           2
c3f22991-8910-4823-86e4-8637520d3952           1
c5440e19-6474-40f0-9306-f4d590035241           1
c6747843-6a62-45f4-9cc6-c9cd85a67a81           1
ce5cf079-859b-43fa-9609-c6bb7e12c6b7           1
df49d870-e940-4a8d-9c68-4cef4e28d916           1
e2df0721-50dd-4f08-8f6b-ab18a0c51b85           1
ec42fc84-51a4-4f32-971a-132852d4fe36           1
ee0d17b8-9535-40ee-985e-8c733c34ca3f           1
f447245d-7239-4808-974c-7fd358f61c2c           1
f5a1c5be-8d36-4fb6-aba2-ba5a2751d3d4           1
f6db05bc-e9ff-454c-983c-fc4a7fd13323           1
fa4c97fc-4a9f-4857-969e-ea9528b2792e           1
fd63f236-3ec3-401d-9fa1-53bda0bd7c0e           1

In [10]:
#Printing the value counts of the said non uniques

conflicts_CustomerID.value_counts()

Age  Gender  Location  IncomeLevel  SignupDate
1    1       1         0            1             17
0    1       1         1            1             14
1    1       1         1            2             11
2    1       1         1            1             11
1    1       1         0            2              1
0    1       1         0            1              1
Name: count, dtype: int64

In [11]:
#Checking the age conflict that has 2 values

age_conflicts = conflicts_CustomerID[conflicts_CustomerID["Age"] > 1]

print(age_conflicts)

                                      Age  Gender  Location  IncomeLevel  \
CustomerID
2cd16dfc-d7b0-47ec-9999-b018daea7f8d    2       1         1            1
3814b8e4-cade-4665-86af-dda3e3628f17    2       1         1            1
48313b18-ccdb-4946-b958-1ebfc92dcc2a    2       1         1            1
50465bde-6a9a-466d-804a-a8f046809a23    2       1         1            1
5050eefe-2392-4d18-b4b6-913d42b9f62b    2       1         1            1
6b2f8f03-ab9e-48a6-a07e-10e794b04fe0    2       1         1            1
7544489f-ec7e-48af-bec6-b6eab94a6e5c    2       1         1            1
76c1d696-0f1c-44b5-b749-8859545658eb    2       1         1            1
9612ee49-09dd-4f55-9524-9eb341efa2b9    2       1         1            1
bbe76a26-234f-4a70-b71f-fa9b183f6353    2       1         1            1
ce5cf079-859b-43fa-9609-c6bb7e12c6b7    2       1         1            1

                                      SignupDate
CustomerID
2cd16dfc-d7b0-47ec-9999-b018daea7f8d           1
3814b8e4-cade-4665-86af-dda3e3628f17           1
48313b18-ccdb-4946-b958-1ebfc92dcc2a           1
50465bde-6a9a-466d-804a-a8f046809a23           1
5050eefe-2392-4d18-b4b6-913d42b9f62b           1
6b2f8f03-ab9e-48a6-a07e-10e794b04fe0           1
7544489f-ec7e-48af-bec6-b6eab94a6e5c           1
76c1d696-0f1c-44b5-b749-8859545658eb           1
9612ee49-09dd-4f55-9524-9eb341efa2b9           1
bbe76a26-234f-4a70-b71f-fa9b183f6353           1
ce5cf079-859b-43fa-9609-c6bb7e12c6b7           1

In [12]:
#Printing the duplicates sorted by customer ID to check the differences in age

print(duplicates[duplicates["CustomerID"].isin(age_conflicts.index)][["CustomerID", "Age"]].sort_values("CustomerID"))

#Analysis: Since there is clearly 1 correct age and 1 outlier age, recommend to drop the outlier row and keep correct age

                                CustomerID      Age
2106  2cd16dfc-d7b0-47ec-9999-b018daea7f8d  Unknown
3051  2cd16dfc-d7b0-47ec-9999-b018daea7f8d     52.0
1238  3814b8e4-cade-4665-86af-dda3e3628f17     32.0
3004  3814b8e4-cade-4665-86af-dda3e3628f17      150
338   48313b18-ccdb-4946-b958-1ebfc92dcc2a  Unknown
3165  48313b18-ccdb-4946-b958-1ebfc92dcc2a     59.0
539   50465bde-6a9a-466d-804a-a8f046809a23       -1
3041  50465bde-6a9a-466d-804a-a8f046809a23     35.0
1768  5050eefe-2392-4d18-b4b6-913d42b9f62b       -1
3145  5050eefe-2392-4d18-b4b6-913d42b9f62b     20.0
174   6b2f8f03-ab9e-48a6-a07e-10e794b04fe0     65.0
3132  6b2f8f03-ab9e-48a6-a07e-10e794b04fe0       -1
2339  7544489f-ec7e-48af-bec6-b6eab94a6e5c     64.0
3138  7544489f-ec7e-48af-bec6-b6eab94a6e5c      150
1355  76c1d696-0f1c-44b5-b749-8859545658eb  Unknown
3150  76c1d696-0f1c-44b5-b749-8859545658eb     34.0
2773  9612ee49-09dd-4f55-9524-9eb341efa2b9  Unknown
3043  9612ee49-09dd-4f55-9524-9eb341efa2b9     28.0
1542  bbe76a26-234f-4a70-b71f-fa9b183f6353     57.0
3178  bbe76a26-234f-4a70-b71f-fa9b183f6353  Unknown
1136  ce5cf079-859b-43fa-9609-c6bb7e12c6b7       -1
3186  ce5cf079-859b-43fa-9609-c6bb7e12c6b7     41.0

In [13]:
#Checking to see outliers

print(df["Age"].value_counts(dropna=False).sort_index())

#EDA: Outliers Identified,

Age
-1          28
-1.0         2
150         31
150.0        2
18.0        59
19.0        49
20.0        50
21.0        49
22.0        41
23.0        54
24.0        39
25.0        57
26.0        72
27.0        58
28.0        52
29.0        44
30.0        44
31.0        49
32.0        48
33.0        38
34.0        70
35.0        41
36.0        56
37.0        56
38.0        54
39.0        47
40.0        52
41.0        46
42.0        53
43.0        60
44.0        37
45.0        58
46.0        55
47.0        51
48.0        51
49.0        55
50.0        42
51.0        49
52.0        59
53.0        58
54.0        45
55.0        60
56.0        53
57.0        72
58.0        55
59.0        56
60.0        53
61.0        57
62.0        71
63.0        51
64.0        55
65.0        50
66.0        53
67.0        52
68.0        66
69.0        52
70.0        58
Unknown     34
NaN        291
Name: count, dtype: int64

In [14]:
#Converting the column 'Age' into numeric values 

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [15]:
#Rechecking the value count of "age" after converting to numeric

print(df["Age"].value_counts(dropna=False).sort_index())

#Analysis: 150 and 150.00 was added together, Unknown values was added to NaN, recommend next move remove outliers. 18 minimum age 70 max age

Age
-1.0       30
 18.0      59
 19.0      49
 20.0      50
 21.0      49
 22.0      41
 23.0      54
 24.0      39
 25.0      57
 26.0      72
 27.0      58
 28.0      52
 29.0      44
 30.0      44
 31.0      49
 32.0      48
 33.0      38
 34.0      70
 35.0      41
 36.0      56
 37.0      56
 38.0      54
 39.0      47
 40.0      52
 41.0      46
 42.0      53
 43.0      60
 44.0      37
 45.0      58
 46.0      55
 47.0      51
 48.0      51
 49.0      55
 50.0      42
 51.0      49
 52.0      59
 53.0      58
 54.0      45
 55.0      60
 56.0      53
 57.0      72
 58.0      55
 59.0      56
 60.0      53
 61.0      57
 62.0      71
 63.0      51
 64.0      55
 65.0      50
 66.0      53
 67.0      52
 68.0      66
 69.0      52
 70.0      58
 150.0     33
 NaN      325
Name: count, dtype: int64

In [16]:
#Creating an acceptable age range 1-100 where outliers will be counted as Nan

df.loc[(df["Age"] < 1) | (df["Age"] > 100), "Age"] = pd.NA

In [17]:
#checking of value count.

print(df["Age"].value_counts(dropna=False).sort_index())

#Analysis: All outliers (-1, 150, and NaN) are all combined into NaN. Recommend: Drop NaN value with duplicated customer ID and impute mean for the rest

Age
18.0     59
19.0     49
20.0     50
21.0     49
22.0     41
23.0     54
24.0     39
25.0     57
26.0     72
27.0     58
28.0     52
29.0     44
30.0     44
31.0     49
32.0     48
33.0     38
34.0     70
35.0     41
36.0     56
37.0     56
38.0     54
39.0     47
40.0     52
41.0     46
42.0     53
43.0     60
44.0     37
45.0     58
46.0     55
47.0     51
48.0     51
49.0     55
50.0     42
51.0     49
52.0     59
53.0     58
54.0     45
55.0     60
56.0     53
57.0     72
58.0     55
59.0     56
60.0     53
61.0     57
62.0     71
63.0     51
64.0     55
65.0     50
66.0     53
67.0     52
68.0     66
69.0     52
70.0     58
NaN     388
Name: count, dtype: int64

In [18]:
#Checking shape of dataset

df.shape

(3200, 6)

In [19]:
#Overriding the current df to clean duplicated CustomerID where age is NaN. 

df = df[~(df["Age"].isna() & df["CustomerID"].duplicated(keep=False))]

In [20]:
#Checking shape of dataset after override

df.shape

#Analysis, 41 rows were dropped where the age was NaN and have a duplicated customer ID

(3159, 6)

In [21]:
#Checking to see remaining sum in "Age" that are NaN

print(df["Age"].isna().sum())

347

In [22]:
#Checking to see the statistical values of numeric column

df.describe()

               Age
count  2812.000000
mean     44.591394
std      15.389286
min      18.000000
25%      31.000000
50%      45.000000
75%      58.000000
max      70.000000

In [23]:
#Calculating for the mean of the "Age", rounded off

mean_age = round(df["Age"].mean())

mean_age

45

In [24]:
#Imputing NaN age with the mean age

df["Age"] = df["Age"].fillna(mean_age)

In [25]:
#Checking age index for the final time to check for any other issues

print(df["Age"].value_counts(dropna=False).sort_index())

Age
18.0     59
19.0     49
20.0     50
21.0     49
22.0     41
23.0     54
24.0     39
25.0     57
26.0     72
27.0     58
28.0     52
29.0     44
30.0     44
31.0     49
32.0     48
33.0     38
34.0     70
35.0     41
36.0     56
37.0     56
38.0     54
39.0     47
40.0     52
41.0     46
42.0     53
43.0     60
44.0     37
45.0    405
46.0     55
47.0     51
48.0     51
49.0     55
50.0     42
51.0     49
52.0     59
53.0     58
54.0     45
55.0     60
56.0     53
57.0     72
58.0     55
59.0     56
60.0     53
61.0     57
62.0     71
63.0     51
64.0     55
65.0     50
66.0     53
67.0     52
68.0     66
69.0     52
70.0     58
Name: count, dtype: int64

In [26]:
#Refreshing duplicates and conflicts_CustomerID and printing new value count of customerID

duplicates = df[df["CustomerID"].duplicated(keep=False)]

conflicts_CustomerID = duplicates.groupby("CustomerID").nunique()

conflicts_CustomerID = conflicts_CustomerID[(conflicts_CustomerID != 1).any(axis=1)]

conflicts_CustomerID.value_counts()

Age  Gender  Location  IncomeLevel  SignupDate
1    1       1         0            1             17
                       1            2             11
                       0            2              1
Name: count, dtype: int64

In [27]:
#Creating a new variable where the customerID is duplicated and income level = 0

income_missing = conflicts_CustomerID[conflicts_CustomerID["IncomeLevel"] == 0]

In [28]:
#Printing values where customerID is duplicated and incomelevel is missing

print(duplicates[duplicates["CustomerID"].isin(income_missing.index)][["CustomerID", "IncomeLevel"]].sort_values("CustomerID"))

#Analysis: Since Income level is NaN and the

                                CustomerID IncomeLevel
1105  06af0246-5f53-45f4-997e-bf42706b11d7         NaN
3061  06af0246-5f53-45f4-997e-bf42706b11d7         NaN
2906  0ab0e741-f4ad-4d82-92c4-b5055b5c5549         NaN
3107  0ab0e741-f4ad-4d82-92c4-b5055b5c5549         NaN
2644  1d26a8ed-88ca-4806-9ec1-7db7ee6a748f         NaN
3191  1d26a8ed-88ca-4806-9ec1-7db7ee6a748f         NaN
2259  22edbbf4-1eb5-4809-bf75-96d82a60bfb7         NaN
3086  22edbbf4-1eb5-4809-bf75-96d82a60bfb7         NaN
1224  29bce3fc-ae36-42db-88d0-d9a87542acfa         NaN
3126  29bce3fc-ae36-42db-88d0-d9a87542acfa         NaN
628   518fa595-22b9-469c-8e3c-96cbfbb41ce7         NaN
3068  518fa595-22b9-469c-8e3c-96cbfbb41ce7         NaN
1870  544dda6b-7d2f-445c-90d9-caeccac0e548         NaN
3130  544dda6b-7d2f-445c-90d9-caeccac0e548         NaN
2904  7120aefc-7d84-4981-b4ec-64e036fba72a         NaN
3180  7120aefc-7d84-4981-b4ec-64e036fba72a         NaN
1614  a0a6e4bc-9637-42b4-875a-7ccc6ebf3b04         NaN
3031  a0a6e4bc-9637-42b4-875a-7ccc6ebf3b04         NaN
1559  b8769321-aa3b-4684-941d-819a58caad05         NaN
3154  b8769321-aa3b-4684-941d-819a58caad05         NaN
2551  c2351d11-59fe-4630-a6df-e01bc343de33         NaN
3079  c2351d11-59fe-4630-a6df-e01bc343de33         NaN
998   c5440e19-6474-40f0-9306-f4d590035241         NaN
3110  c5440e19-6474-40f0-9306-f4d590035241         NaN
2341  c6747843-6a62-45f4-9cc6-c9cd85a67a81         NaN
3072  c6747843-6a62-45f4-9cc6-c9cd85a67a81         NaN
1633  df49d870-e940-4a8d-9c68-4cef4e28d916         NaN
3053  df49d870-e940-4a8d-9c68-4cef4e28d916         NaN
2250  e2df0721-50dd-4f08-8f6b-ab18a0c51b85         NaN
3175  e2df0721-50dd-4f08-8f6b-ab18a0c51b85         NaN
2498  ee0d17b8-9535-40ee-985e-8c733c34ca3f         NaN
3098  ee0d17b8-9535-40ee-985e-8c733c34ca3f         NaN
380   f6db05bc-e9ff-454c-983c-fc4a7fd13323         NaN
3059  f6db05bc-e9ff-454c-983c-fc4a7fd13323         NaN
1970  fa4c97fc-4a9f-4857-969e-ea9528b2792e         NaN
3187  fa4c97fc-4a9f-4857-969e-ea9528b2792e         NaN

In [29]:
#Creating a variable for Signup date duplicates

signup_conflicts = conflicts_CustomerID[conflicts_CustomerID["SignupDate"] > 1]

In [30]:
#Printing duplicates in CustomerID where signup date does not match 

print(duplicates[duplicates["CustomerID"].isin(signup_conflicts.index)][["CustomerID", "SignupDate"]].sort_values("CustomerID"))

                                CustomerID  SignupDate
1536  08995799-8d0f-40d6-986b-452074709b5f  15/11/2019
3024  08995799-8d0f-40d6-986b-452074709b5f  2020-03-28
304   1e9e7dcb-e612-46d3-bae6-0c2f47fa0220  2022-07-28
3085  1e9e7dcb-e612-46d3-bae6-0c2f47fa0220  07/11/2019
754   29436bcf-d6f8-44d1-a856-0794abb562ab  2021-09-01
3083  29436bcf-d6f8-44d1-a856-0794abb562ab  12/03/2020
1581  7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc  07/01/2021
3183  7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc  2022-07-23
2082  83355281-fda3-4776-9f9d-a812243c3b56  23/02/2022
3062  83355281-fda3-4776-9f9d-a812243c3b56  2024-04-15
911   835384f5-c976-481d-8961-cc827dc62c6b  01/07/2019
3087  835384f5-c976-481d-8961-cc827dc62c6b  2023-09-30
999   890f10ce-36f6-4993-9a2e-a00dfdf01609  2022-09-04
3149  890f10ce-36f6-4993-9a2e-a00dfdf01609  27/05/2021
1684  89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2  2022-03-03
3119  89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2  18/01/2024
225   b72f2a59-aab0-447d-bb31-9bdc1405cc72  10/06/2024
3162  b72f2a59-aab0-447d-bb31-9bdc1405cc72  2021-09-19
1383  bb07fa4a-8680-4b77-b1ad-5d2f67570252  06/08/2019
3078  bb07fa4a-8680-4b77-b1ad-5d2f67570252  2020-11-06
160   bbf7c36f-3745-4d3a-9e33-f927c2755f65  07/07/2019
3195  bbf7c36f-3745-4d3a-9e33-f927c2755f65  2023-02-17
2551  c2351d11-59fe-4630-a6df-e01bc343de33  15/06/2022
3079  c2351d11-59fe-4630-a6df-e01bc343de33  2022-02-04

In [31]:
#Printing Null values in Signup date

print(df["SignupDate"].isna().sum())

0

In [32]:
#Converting signup date to a consistent date format

df["SignupDate"] = pd.to_datetime(df["SignupDate"], format="mixed", dayfirst=True, errors="coerce")

In [33]:
#Printing Null values in Signup date after the convert

print(df["SignupDate"].isna().sum())

0

In [34]:
df

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,45.0,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-10-06
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24
...,...,...,...,...,...,...
3194,40c2909d-983b-4c95-a737-2022acba98ee,28.0,Male,Josephborough,High,2020-02-14
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17
3196,0ef84cc6-0b4c-4c56-bdaa-d6b725ccc08e,40.0,Male,Lisaside,Medium,2022-07-23
3198,43ec68f5-4305-4b40-8ced-a187d00bb3f5,26.0,Female,Carrilloport,Low,2022-09-26
3199,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-09-11

In [35]:
# Refresh duplicated CustomerID records
duplicates = df[df["CustomerID"].duplicated(keep=False)]

# Refresh CustomerID conflicts
conflicts_CustomerID = duplicates.groupby("CustomerID").nunique()

conflicts_CustomerID = conflicts_CustomerID[(conflicts_CustomerID != 1).any(axis=1)]

In [36]:
# Creating a variable for signup conflicts
signup_conflicts = conflicts_CustomerID[conflicts_CustomerID["SignupDate"] > 1]

In [37]:
# Print duplicates where SignupDate does not match

print(duplicates[duplicates["CustomerID"].isin(signup_conflicts.index)][["CustomerID", "SignupDate"]].sort_values("CustomerID"))

                                CustomerID SignupDate
1536  08995799-8d0f-40d6-986b-452074709b5f 2019-11-15
3024  08995799-8d0f-40d6-986b-452074709b5f 2020-03-28
304   1e9e7dcb-e612-46d3-bae6-0c2f47fa0220 2022-07-28
3085  1e9e7dcb-e612-46d3-bae6-0c2f47fa0220 2019-11-07
754   29436bcf-d6f8-44d1-a856-0794abb562ab 2021-01-09
3083  29436bcf-d6f8-44d1-a856-0794abb562ab 2020-03-12
1581  7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc 2021-01-07
3183  7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc 2022-07-23
2082  83355281-fda3-4776-9f9d-a812243c3b56 2022-02-23
3062  83355281-fda3-4776-9f9d-a812243c3b56 2024-04-15
911   835384f5-c976-481d-8961-cc827dc62c6b 2019-07-01
3087  835384f5-c976-481d-8961-cc827dc62c6b 2023-09-30
999   890f10ce-36f6-4993-9a2e-a00dfdf01609 2022-04-09
3149  890f10ce-36f6-4993-9a2e-a00dfdf01609 2021-05-27
1684  89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2 2022-03-03
3119  89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2 2024-01-18
225   b72f2a59-aab0-447d-bb31-9bdc1405cc72 2024-06-10
3162  b72f2a59-aab0-447d-bb31-9bdc1405cc72 2021-09-19
1383  bb07fa4a-8680-4b77-b1ad-5d2f67570252 2019-08-06
3078  bb07fa4a-8680-4b77-b1ad-5d2f67570252 2020-06-11
160   bbf7c36f-3745-4d3a-9e33-f927c2755f65 2019-07-07
3195  bbf7c36f-3745-4d3a-9e33-f927c2755f65 2023-02-17
2551  c2351d11-59fe-4630-a6df-e01bc343de33 2022-06-15
3079  c2351d11-59fe-4630-a6df-e01bc343de33 2022-04-02

In [38]:
#Sorting the values of signupDate to make the earlier date on top

df = df.sort_values("SignupDate")

#Get CustomerIDs with conflicting SignupDates
signup_ids = signup_conflicts.index

#Combining the non-conflicting records with the corrected SignupDate records
df = pd.concat([
    df[~df["CustomerID"].isin(signup_ids)],
    df[df["CustomerID"].isin(signup_ids)].drop_duplicates(
        subset="CustomerID", keep="last"
    )
], ignore_index=True)

# Reason: Opted to keep the last since this is the latest data that the person made.

In [39]:
print("Duplicate CustomerIDs:", df["CustomerID"].duplicated().sum())
print("Current Shape:", df.shape)

Duplicate CustomerIDs: 162
Current Shape: (3147, 6)

In [40]:
#Refreshing duplicates and conflicts_CustomerID and printing new value count of customerID

duplicates = df[df["CustomerID"].duplicated(keep=False)]

conflicts_CustomerID = duplicates.groupby("CustomerID").nunique()

conflicts_CustomerID = conflicts_CustomerID[(conflicts_CustomerID != 1).any(axis=1)]

conflicts_CustomerID.value_counts()

Age  Gender  Location  IncomeLevel  SignupDate
1    1       1         0            1             17
Name: count, dtype: int64

In [41]:
#Printing duplicated customerID with null in incomelevel

df[(df["CustomerID"].duplicated(keep=False)) & (df["IncomeLevel"].isna())].sort_values("CustomerID")

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
2094,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
2095,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
69,0ab0e741-f4ad-4d82-92c4-b5055b5c5549,26.0,Male,South Robertberg,NaN,2019-07-14
70,0ab0e741-f4ad-4d82-92c4-b5055b5c5549,26.0,Male,South Robertberg,NaN,2019-07-14
364,1d26a8ed-88ca-4806-9ec1-7db7ee6a748f,32.0,Female,East Cindy,NaN,2020-01-25
369,1d26a8ed-88ca-4806-9ec1-7db7ee6a748f,32.0,Female,East Cindy,NaN,2020-01-25
3048,22edbbf4-1eb5-4809-bf75-96d82a60bfb7,45.0,Female,Cherylfort,NaN,2024-06-28
3049,22edbbf4-1eb5-4809-bf75-96d82a60bfb7,45.0,Female,Cherylfort,NaN,2024-06-28
2175,29bce3fc-ae36-42db-88d0-d9a87542acfa,38.0,Female,West Deborahbury,NaN,2023-01-15
2176,29bce3fc-ae36-42db-88d0-d9a87542acfa,38.0,Female,West Deborahbury,NaN,2023-01-15
503,518fa595-22b9-469c-8e3c-96cbfbb41ce7,47.0,Female,North Brianport,NaN,2020-04-21
504,518fa595-22b9-469c-8e3c-96cbfbb41ce7,47.0,Female,North Brianport,NaN,2020-04-21
1399,544dda6b-7d2f-445c-90d9-caeccac0e548,58.0,Female,Robertsfort,NaN,2021-10-03
1401,544dda6b-7d2f-445c-90d9-caeccac0e548,58.0,Female,Robertsfort,NaN,2021-10-03
2165,7120aefc-7d84-4981-b4ec-64e036fba72a,45.0,Female,Brownbury,NaN,2023-01-10
2166,7120aefc-7d84-4981-b4ec-64e036fba72a,45.0,Female,Brownbury,NaN,2023-01-10
1721,a0a6e4bc-9637-42b4-875a-7ccc6ebf3b04,53.0,Female,Gwendolynton,NaN,2022-04-07
1724,a0a6e4bc-9637-42b4-875a-7ccc6ebf3b04,53.0,Female,Gwendolynton,NaN,2022-04-07
2974,b8769321-aa3b-4684-941d-819a58caad05,54.0,Female,East Matthew,NaN,2024-04-26
2975,b8769321-aa3b-4684-941d-819a58caad05,54.0,Female,East Matthew,NaN,2024-04-26
1938,c5440e19-6474-40f0-9306-f4d590035241,69.0,Female,Lake Brandon,NaN,2022-08-14
1939,c5440e19-6474-40f0-9306-f4d590035241,69.0,Female,Lake Brandon,NaN,2022-08-14
1861,c6747843-6a62-45f4-9cc6-c9cd85a67a81,52.0,Female,Jamesview,NaN,2022-07-01
1863,c6747843-6a62-45f4-9cc6-c9cd85a67a81,52.0,Female,Jamesview,NaN,2022-07-01
179,df49d870-e940-4a8d-9c68-4cef4e28d916,40.0,Male,Ericside,NaN,2019-09-27
181,df49d870-e940-4a8d-9c68-4cef4e28d916,40.0,Male,Ericside,NaN,2019-09-27
1839,e2df0721-50dd-4f08-8f6b-ab18a0c51b85,29.0,Female,Port Linda,NaN,2022-06-15
1840,e2df0721-50dd-4f08-8f6b-ab18a0c51b85,29.0,Female,Port Linda,NaN,2022-06-15
1722,ee0d17b8-9535-40ee-985e-8c733c34ca3f,57.0,Female,Levyport,NaN,2022-04-07
1723,ee0d17b8-9535-40ee-985e-8c733c34ca3f,57.0,Female,Levyport,NaN,2022-04-07
3044,f6db05bc-e9ff-454c-983c-fc4a7fd13323,43.0,Male,Port Carrie,NaN,2024-06-24
3045,f6db05bc-e9ff-454c-983c-fc4a7fd13323,43.0,Male,Port Carrie,NaN,2024-06-24
1648,fa4c97fc-4a9f-4857-969e-ea9528b2792e,57.0,Male,East Michaelchester,NaN,2022-02-27
1651,fa4c97fc-4a9f-4857-969e-ea9528b2792e,57.0,Male,East Michaelchester,NaN,2022-02-27

In [42]:
#Creating a variable for the mode of income
mode_income = df["IncomeLevel"].mode()[0]

Income_level_count = df["IncomeLevel"].value_counts()
print(Income_level_count)
print(mode_income)

IncomeLevel
High      989
Low       966
Medium    892
Name: count, dtype: int64
High

In [43]:
#Filling NaN values in income level "unspecified"

df["IncomeLevel"] = df["IncomeLevel"].fillna("Unspecified")

In [44]:
#Checking for empty values in Income level

df["IncomeLevel"].isna().sum()

np.int64(0)

In [45]:
#Checking for duplicated rows globally

df.duplicated().sum()

np.int64(162)

In [46]:
df.isna().sum()

CustomerID     0
Age            0
Gender         0
Location       0
IncomeLevel    0
SignupDate     0
dtype: int64

In [47]:
#Dropping duplicated rows

df_cleaned = df.drop_duplicates()

In [48]:
#Final checking of df_cleaned before exporting

In [49]:
#Checking for null values

df_cleaned.isna().sum()

CustomerID     0
Age            0
Gender         0
Location       0
IncomeLevel    0
SignupDate     0
dtype: int64

In [50]:
#Checking for info

df_cleaned.info()

<class 'pandas.DataFrame'>
Index: 2985 entries, 0 to 3146
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   2985 non-null   str
 1   Age          2985 non-null   float64
 2   Gender       2985 non-null   str
 3   Location     2985 non-null   str
 4   IncomeLevel  2985 non-null   str
 5   SignupDate   2985 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 333.9 KB

In [51]:
#Checking unique values in Gender & Income Level

unique_gender = df_cleaned["Gender"].value_counts()
unique_income_level = df_cleaned["IncomeLevel"].value_counts()

print("Value count for Gender: " , unique_gender)
print()
print ("Value count for Income Level: " , unique_income_level)

Value count for Gender:  Gender
Female    1507
Male      1478
Name: count, dtype: int64

Value count for Income Level:  IncomeLevel
High           933
Low            911
Medium         858
Unspecified    283
Name: count, dtype: int64

In [52]:
#Checking unique values in Age

unique_age = df_cleaned["Age"].value_counts().sort_index()

unique_age

Age
18.0     55
19.0     48
20.0     48
21.0     45
22.0     38
23.0     52
24.0     36
25.0     55
26.0     64
27.0     54
28.0     50
29.0     41
30.0     43
31.0     45
32.0     43
33.0     33
34.0     63
35.0     39
36.0     55
37.0     54
38.0     51
39.0     46
40.0     49
41.0     43
42.0     49
43.0     56
44.0     36
45.0    400
46.0     50
47.0     45
48.0     48
49.0     50
50.0     41
51.0     48
52.0     53
53.0     53
54.0     43
55.0     56
56.0     51
57.0     67
58.0     53
59.0     54
60.0     46
61.0     55
62.0     70
63.0     49
64.0     52
65.0     47
66.0     50
67.0     49
68.0     60
69.0     48
70.0     56
Name: count, dtype: int64

In [53]:
#Checking unique values in Location

unique_location = df_cleaned["Location"].value_counts().sort_index()

print(unique_location)

#Analysis: 2686 Unique locations

Location
Aaronton          1
Abbottside        1
Acevedofort       1
Adamsfort         1
Adamshire         3
                 ..
Zacharyfort       1
Zacharymouth      1
Zacharyside       1
Zacharyview       1
Zimmermanville    1
Name: count, Length: 2686, dtype: int64

In [54]:
#Checking for duplicates in final df

df_cleaned.duplicated().sum()

np.int64(0)

In [55]:
#Checking shape of final df

df_cleaned.shape

(2985, 6)

In [57]:
#Checking describe of age

df_cleaned["Age"].describe()

count    2985.000000
mean       44.662647
std        14.489079
min        18.000000
25%        33.000000
50%        45.000000
75%        57.000000
max        70.000000
Name: Age, dtype: float64

In [58]:
#EXPORTING CLEANED FILE AS A CSV

df_cleaned.to_csv("Customer_Demographics_Cleaned.csv", index=False)

In [66]:
#Getting mode, range, variance, standard deviation for EDA

age_mode = df_cleaned["Age"].mode()[0]
age_range = df_cleaned["Age"].max() - df_cleaned["Age"].min()
age_variance = df_cleaned["Age"].var()
age_std = df_cleaned["Age"].std()

print("Mode:", age_mode)
print("Range:", age_range)
print("Variance:", age_variance)
print("Standard Deviation:", age_std)

Mode: 45.0
Range: 52.0
Variance: 209.93340653221426
Standard Deviation: 14.489078871074389

In [67]:
print("=== Customer Demographics ===")

print("\nGender:")
print(df_cleaned["Gender"].value_counts())

print("\nIncome Level:")
print(df_cleaned["IncomeLevel"].value_counts())

print("\nLocation:")
print(df_cleaned["Location"].value_counts())

print("\nAge:")
print(df_cleaned["Age"].value_counts().sort_index())

=== Customer Demographics ===

Gender:
Gender
Female    1507
Male      1478
Name: count, dtype: int64

Income Level:
IncomeLevel
High      1216
Low        911
Medium     858
Name: count, dtype: int64

Location:
Location
Port Michael      5
Michaelton        4
Michaelville      4
West David        4
Port Eric         4
                 ..
Brianmouth        1
Roberttown        1
Stricklandport    1
Ashleychester     1
West Jason        1
Name: count, Length: 2686, dtype: int64

Age:
Age
18.0     55
19.0     48
20.0     48
21.0     45
22.0     38
23.0     52
24.0     36
25.0     55
26.0     64
27.0     54
28.0     50
29.0     41
30.0     43
31.0     45
32.0     43
33.0     33
34.0     63
35.0     39
36.0     55
37.0     54
38.0     51
39.0     46
40.0     49
41.0     43
42.0     49
43.0     56
44.0     36
45.0    400
46.0     50
47.0     45
48.0     48
49.0     50
50.0     41
51.0     48
52.0     53
53.0     53
54.0     43
55.0     56
56.0     51
57.0     67
58.0     53
59.0     54
60.0     46
61.0     55
62.0     70
63.0     49
64.0     52
65.0     47
66.0     50
67.0     49
68.0     60
69.0     48
70.0     56
Name: count, dtype: int64